name: shelfpeople
description: a people api
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  shelf: 
  shelf_router: 
  supabase: 
  crypt:
  dart_jsonwebtoken:

dev_dependencies:
  build_runner:
  build_test: 
  build_web_compilers: